### ISSUE TITLE
docker-compose.yml, mise à jour command uvicorn --reload-dir app

### ISSUE THREAD

**Issue by vincentporte** [vjousse/fastapi-beginners-guide#5]
docker-compose.yml : mise à jour de la commande uvicorn. ajout du param --reload-dir app

```
  web:
    build: .
    restart: always
    volumes:
      - ./app:/fastapi-guide/app
    command: uvicorn app.main:app --reload --reload-dir app --host 0.0.0.0
```

Command Line
```
~/.../Products/fastapi-beginners-guide >>> docker-compose up  
Starting fastapi-beginners-guide_web_1 ... done
Starting fastapi-beginners-guide_nginx_1 ... done
Attaching to fastapi-beginners-guide_web_1, fastapi-beginners-guide_nginx_1
web_1    | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
web_1    | INFO:     Started reloader process [1] using watchgod
web_1    | INFO:     Started server process [8]
web_1    | INFO:     Waiting for application startup.
web_1    | INFO:     Application startup complete.
web_1    | INFO:uvicorn.error:Application startup complete.

```
les logs affichent "INFO:uvicorn.error:Application startup complete." sans que ça gene le fonctionnement de l'app. quelle peut être l'origine de cette erreur?
